<?php

/**
 * @file classified_tweaks.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function classified_tweaks_form_classified_node_form_alter(&$form, &$form_state) {
  // If there's only one option, display it as a message.
  if (count($form['expires_fs']['expire_mode']['#options']) == 1) {
    $option = $form['expires_fs']['expire_mode']['#options'];
    $form['expires_fs']['expire_mode']['#type'] = 'value';
    $form['expires_fs']['expire_mode']['#value'] = key($option);
    $form['expires_fs']['#description'] = current($option);
  }
  // On edit forms, don't give the user the option to reset its ad expire date.
  // Of course, administrators do as they please.
  global $user;
  if ($user->uid != 1 && !empty($form['#node']->nid)) {
    $form['expires_fs']['expire_mode']['#type'] = 'value';
    $form['expires_fs']['expire_mode']['#value'] = 'node';
    if (empty($form['#node']->status)) {
      $form['expires_fs']['expire_mode']['#value'] = 'reset';
    }
  }
}
