<?php

/**
 * @file classified_tweaks.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function classified_tweaks_form_classified_node_form_alter(&$form, &$form_state) {
  // On edit forms, don't give the user the option to reset its ad expire date.
  // Of course, administrators do as they please.
  global $user;
  if ($user->uid != 1) {
    $form['expires_fs']['expire_mode']['#type'] = 'value';
    $form['expires_fs']['expire_mode']['#value'] = 'reset';
    unset($form['expires_fs']['#type']);
  }

  if (!empty($form['#node']->nid)) {
    // If node is not expired, don't reset its expire date.
    if ($user->uid != 1 && $form['#node']->status) {
      $form['expires_fs']['expire_mode']['#value'] = 'node';
    }
    // Inform the user about expiration time resetting.
    $form['expire_message'] = array(
      '#type' => 'item',
      '#weight' => $form['title']['#weight'] + 0.001,
    );
    $message = $form['#node']->status ?
      t('This ad will expire in @time.',
        array('@time' => format_interval($form['#node']->expires - REQUEST_TIME, 2))) :
      t('Expired');
    $form['expire_message']['#markup'] = '<p>' . $message .'</p>';
    if ($form['#node']->status) {
      // $form['expire_message']['#markup'] .= '<p>' . t('Click "Save" to keep your edits.') .'</p>';
      // $form['expire_message']['#markup'] .= '<p>' . t('Click "Cancel" to go back to the ads list.') .'</p>';
      // $form['expire_message']['#markup'] .= '<p>' . t('Click "Unpublish" to hide your ad. It will be kept in the database until it expires.') .'</p>';
    } else {
      // $form['expire_message']['#markup'] .= '<p>' . t('Click "Renew" to post the ad again') .'</p>';
      // $form['expire_message']['#markup'] .= '<p>' . t('Click "Keep Unpublished" to hold on to the ad without posting it again.') .'</p>';
      $form['expire_message']['#markup'] .= '<p>' . t('This ad has expired or you unpublished it.') . '</p>';
      $form['expire_message']['#markup'] .= '<p>' . t('If the ad expired you may renew it by clicking "Renew." If you unpublished it then "Renew" will not work until the ad has completely expired. Clicking "Renew" in any case will save any changes you wish to make.') . '</p>';
      $form['actions']['submit']['#value'] = t('Renew');
    }
    // $form['expire_message']['#markup'] .= '<p>' . t('Click "Delete" to permanently delete this ad.') .'</p>';
  }

  // Add cancel button.
  $cancel = (!empty($form['#node']->nid) && $form['#node']->status == 0) ? t('Keep Unpublished') : t('Cancel');
  $form['actions']['cancel'] = array(
    '#value' => $cancel,
    '#weight' => $form['actions']['submit']['#weight'] + 0.001,
    '#type' => 'submit',
    '#limit_validation_errors' => array(),
    '#submit' => array('classified_tweaks_node_form_cancel'),
  );
}

function classified_tweaks_node_form_cancel($form, &$form_state) {
  drupal_goto('classified');
}

/**
 * Implements hook_node_presave().
 */
function classified_tweaks_node_presave($node) {
  if (!empty($node->original) && $node->original->status == 0) {
    // When an ad is recovered from the grace period, it bumps its timestamp.
    $node->created = $node->changed;
  }
}
